name: Test

on: [ push ]
# on:
#   push:
#     branches:
#       - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run Test environment setup
        run: make test-setup

      - name: Run Test
        run: make test

      - name: Run Test environment teardown
        if: always()
        run: make test-teardown

